### ISSUE TITLE
No getter for `showTitle` in titleParametersDidChange 

### ISSUE THREAD

**Issue by WalshyDev** [WalshyDev/StreamDeck4J#3]
Also an exception on this event

```java
java.lang.ClassCastException: java.desktop/sun.font.AttributeMap cannot be cast to java.base/java.util.HashMap

    at com.walshydev.streamdeck4j.PluginImpl.getFont(PluginImpl.java:205)
    at com.walshydev.streamdeck4j.PluginImpl.handleEvent(PluginImpl.java:323)
    at com.walshydev.streamdeck4j.EventTests.testTitleParametersDidChange(EventTests.java:215)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
    at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
```

**Comment by WalshyDev** [comment]
Fixed in bb1547333f366996abfac238594cc81fd9f5bc96 and 70913d3b298c1399bb7e696c4f2ac46f38e803a9
